# Generated by Django 5.2.8 on 2025-11-28 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30, null=True)),
                ('passport', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.IntegerField()),
                ('signing_date', models.DateField()),
                ('signing_place', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3_shemelin.client')),
            ],
        ),
    ]
